
name: DevSecOps Security Pipeline

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  bandit:
    name: Python Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Show Python file
        run: |
          pwd
          ls -la
          cat app.py

      - name: Run Bandit
        run: bandit app.py

  trivy:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan Docker configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: 
          severity: HIGH,CRITICAL
          exit-code: "0"
          format: table
          severity: HIGH,CRITICAL
          exit-code: "0"
          format: table
